### ISSUE TITLE
invalid mode (wb) or filename error msg -  wubi16046r333 in windows 10

### ISSUE THREAD

**Issue by Monikaprak** [hakuna-m/wubiuefi#150]
Hi, 
I trying to install ubuntu16.0.04 LTS in windows 10.
I downloaded ubuntu lts iso from http://releases.ubuntu.com/16.04/
Installed wubi16046r333 installer.

But I am getting the following error
invalid mode (wb) or filename

from the log:
5-22 16:29 ERROR  TaskList: [Errno 22] invalid mode ('wb') or filename: 'C:\\wubildr'
Traceback (most recent call last):
  File "\lib\wubi\backends\common\tasklist.py", line 197, in __call__
  File "\lib\wubi\backends\win32\backend.py", line 791, in modify_bcd
  File "\lib\shutil.py", line 83, in copyfile
IOError: [Errno 22] invalid mode ('wb') or filename: 'C:\\wubildr'
05-22 16:29 DEBUG  TaskList: # Cancelling tasklist
05-22 16:29 DEBUG  TaskList: New task modify_bcd
05-22 16:29 ERROR  root: [Errno 22] invalid mode ('wb') or filename: 'C:\\wubildr'
Traceback (most recent call last):
  File "\lib\wubi\application.py", line 58, in run
  File "\lib\wubi\application.py", line 132, in select_task
  File "\lib\wubi\application.py", line 158, in run_installer
  File "\lib\wubi\backends\common\tasklist.py", line 197, in __call__
  File "\lib\wubi\backends\win32\backend.py", line 791, in modify_bcd
  File "\lib\shutil.py", line 83, in copyfile
IOError: [Errno 22] invalid mode ('wb') or filename: 'C:\\wubildr'
05-22 16:29 DEBUG  TaskList: ## Finished modify_bootloader
05-22 16:29 DEBUG  TaskList: # Finished tasklist

**Comment by hakuna-m** [comment]
> [Errno 22] invalid mode ('wb') or filename: 'C:\wubildr'

First of all, it is a common [Python](https://en.wikipedia.org/wiki/Python_(programming_language)) error message but it is not really a common Wubi error message.

In most cases the reason for the Python error message are invalid characters within filename. But for Wubi(uefi) the filename  'C:\wubildr' does not depend on your Wubi configuration. So it should occur on other systems, too. But as far as I know, there are no further reports. 

So maybe the reason are some settings for drive C: . e.g. Is drive C: your system drive as expected by Wubi(uefi)?
