### ISSUE TITLE
Dont can install Ubuntu (Windows 8.1)

### ISSUE THREAD

**Issue by amiller911** [hakuna-m/wubiuefi#166]
Dont can install Lubuntu 16.04.6

I get error:

`10-17 20:54 DEBUG  downloader: Download start filename=D:\ubuntu\install\lubuntu-16.04.6-desktop-amd64.iso, url=http://cdimage.ubuntu.com/lubuntu/releases/16.04.6/release/lubuntu-16.04.6-desktop-amd64.iso, basename=lubuntu-16.04.6-desktop-amd64.iso, length=977272832, text=None
10-17 21:27 DEBUG  TaskList: ### Finished download
10-17 21:27 DEBUG  downloader: download finished (read 977272832 bytes)
10-17 21:27 DEBUG  TaskList: New task check_iso
10-17 21:27 DEBUG  TaskList: ### Running check_iso...
10-17 21:27 DEBUG  CommonBackend: Checking D:\ubuntu\install\lubuntu-16.04.6-desktop-amd64.iso
10-17 21:27 DEBUG  Distro:   checking Lubuntu ISO D:\ubuntu\install\lubuntu-16.04.6-desktop-amd64.iso
10-17 21:27 ERROR  WindowsBackend: Error executing command
>>command=C:\Users\Alex\AppData\Local\Temp\pyl3B6F.tmp\bin\7z.exe l D:\ubuntu\install\lubuntu-16.04.6-desktop-amd64.iso
>>retval=2
>>stderr=

7-Zip 9.20  Copyright (c) 1999-2010 Igor Pavlov  2010-11-18

Error: D:\ubuntu\install\lubuntu-16.04.6-desktop-amd64.iso: The process cannot access the file because it is being used by another process.

Errors: 1
>>stdout=
Traceback (most recent call last):
  File "\lib\wubi\backends\win32\backend.py", line 521, in get_iso_file_names
  File "\lib\wubi\backends\common\utils.py", line 68, in run_command
Exception: Error executing command
>>command=C:\Users\Alex\AppData\Local\Temp\pyl3B6F.tmp\bin\7z.exe l D:\ubuntu\install\lubuntu-16.04.6-desktop-amd64.iso
>>retval=2
>>stderr=

7-Zip 9.20  Copyright (c) 1999-2010 Igor Pavlov  2010-11-18

Error: D:\ubuntu\install\lubuntu-16.04.6-desktop-amd64.iso: The process cannot access the file because it is being used by another process.

Errors: 1
>>stdout=
10-17 21:27 DEBUG  WindowsBackend: command >>C:\Users\Alex\AppData\Local\Temp\pyl3B6F.tmp\bin\7z.exe l D:\ubuntu\install\lubuntu-16.04.6-desktop-amd64.iso
10-17 21:27 DEBUG  Distro:     does not contain any file
10-17 21:27 DEBUG  TaskList: ### Finished check_iso
10-17 21:27 ERROR  TaskList: [Error 32] The process cannot access the file because it is being used by another process: u'D:\\ubuntu\\install\\lubuntu-16.04.6-desktop-amd64.iso'
Traceback (most recent call last):
  File "\lib\wubi\backends\common\tasklist.py", line 197, in __call__
  File "\lib\wubi\backends\common\backend.py", line 609, in get_iso
  File "\lib\wubi\backends\common\backend.py", line 452, in download_iso
WindowsError: [Error 32] The process cannot access the file because it is being used by another process: u'D:\\ubuntu\\install\\lubuntu-16.04.6-desktop-amd64.iso'
10-17 21:27 DEBUG  TaskList: # Cancelling tasklist
10-17 21:27 DEBUG  TaskList: # Finished tasklist
10-17 21:27 ERROR  root: [Error 32] The process cannot access the file because it is being used by another process: u'D:\\ubuntu\\install\\lubuntu-16.04.6-desktop-amd64.iso'
Traceback (most recent call last):
  File "\lib\wubi\application.py", line 58, in run
  File "\lib\wubi\application.py", line 132, in select_task
  File "\lib\wubi\application.py", line 158, in run_installer
  File "\lib\wubi\backends\common\tasklist.py", line 197, in __call__
  File "\lib\wubi\backends\common\backend.py", line 609, in get_iso
  File "\lib\wubi\backends\common\backend.py", line 452, in download_iso
WindowsError: [Error 32] The process cannot access the file because it is being used by another process: u'D:\\ubuntu\\install\\lubuntu-16.04.6-desktop-amd64.iso'
`

How can fix my problem?

**Comment by hakuna-m** [comment]
> The process cannot access the file because it is being used by another process.

In most cases that error message appears as subsequent error of other errors. 

1) Try to copy the downloaded ISO from D:\ubuntu\install\lubuntu-16.04.6-desktop-amd64.iso to another place outside folder D:\ubuntu.
2) Try to run Wubiuefi with the pre-downloaded ISO. see [How can I use a pre-downloaded ISO file ?](https://github.com/hakuna-m/wubiuefi/wiki/FAQ#how-can-i-use-a-pre-downloaded-iso-file-)

BTW: Which Wubiuefi version did you use ?

**Comment by midaspt** [comment]
I'm getting the same error on **Windows 10** with **Wubiuefi v18.04.02rev333**.

A copy of the auto-generated error log is at <https://pastebin.com/xsBgd7jc>.

Any help appreciated.

**Comment by hakuna-m** [comment]
> I consistently get the same error on **Windows 10** with **Wubiuefi v18.04.02rev333**

see #182 or #180
