### ISSUE TITLE
ERROR  TaskList: substring not found on Windows 10

### ISSUE THREAD

**Issue by lzanchin** [hakuna-m/wubiuefi#246]
Trying to install the latest version available of Ubuntu here with Wubi UEFI but facing the following problem.

11-03 01:07 DEBUG  TaskList: ## Finished choose_disk_sizes
11-03 01:07 DEBUG  TaskList: ## Running create_preseed...
11-03 01:07 DEBUG  TaskList: ## Finished create_preseed
11-03 01:07 DEBUG  TaskList: ## Running modify_bootloader...
11-03 01:07 DEBUG  TaskList: New task modify_bcd
11-03 01:07 DEBUG  TaskList: ### Running modify_bcd...
11-03 01:07 DEBUG  WindowsBackend: modify_bcd Drive(C: hd 104799.769531 mb free ntfs)
11-03 01:07 DEBUG  WindowsBackend: EFI boot
11-03 01:07 ERROR  TaskList: substring not found
Traceback (most recent call last):
  File "\lib\wubi\backends\common\tasklist.py", line 197, in __call__
  File "\lib\wubi\backends\win32\backend.py", line 812, in modify_bcd
  File "\lib\wubi\backends\win32\backend.py", line 580, in modify_EFI_folder
ValueError: substring not found
11-03 01:07 DEBUG  TaskList: # Cancelling tasklist
11-03 01:07 DEBUG  TaskList: New task modify_bcd
11-03 01:07 ERROR  root: substring not found
Traceback (most recent call last):
  File "\lib\wubi\application.py", line 58, in run
  File "\lib\wubi\application.py", line 132, in select_task
  File "\lib\wubi\application.py", line 158, in run_installer
  File "\lib\wubi\backends\common\tasklist.py", line 197, in __call__
  File "\lib\wubi\backends\win32\backend.py", line 812, in modify_bcd
  File "\lib\wubi\backends\win32\backend.py", line 580, in modify_EFI_folder
ValueError: substring not found
11-03 01:07 DEBUG  TaskList: New task modify_bcd
11-03 01:07 DEBUG  TaskList: ## Finished modify_bootloader
11-03 01:07 DEBUG  TaskList: # Finished tasklist

It seems like the root cause of the issue is because I have no "device" variable in mine Windows Boot Manager

![image](https://user-images.githubusercontent.com/14079844/97926845-f5809f00-1db7-11eb-91c0-a4bc5bcb9d01.png)

**Comment by hakuna-m** [comment]
> It seems like the root cause of the issue is because I have no "device" variable in mine Windows Boot Manager

You are right. As I wrote in https://github.com/hakuna-m/wubiuefi/issues/3#issuecomment-205018636

> IMHO it is better, if you set the EFI partition for your Windows as [the documentation of Microsoft](https://technet.microsoft.com/en-us/library/dn336950.aspx) says.
> 
> In your case, you can use on Windows command prompt as admin:
> 
> ```
> mountvol s: /s
> bcdedit /set {bootmgr} device partition=s:
> ```
> 
> After that, your device entry should be changed from **unknown** to **partition=s:**
> 
> If you unmount your partition with
> `mountvol s: /d`
> 
> the device entry should be changed from **partition=s:** to a Windows disk/partition name/number, something like **partition=\Device\HarddiskVolume1**

**Comment by lzanchin** [comment]
Thank you @hakuna-m . I will give it a try later today and update the issue with the results afterwards.
