### ISSUE TITLE
casper/initrd.lz4 is NOT supported?

### ISSUE THREAD

**Issue by shohtanedu** [hakuna-m/wubiuefi#287]
Hi. I have a question.
I want to dualboot Zorin OS 16 by wubiuefi, but wubiuefi is not loaded Zorin iso file. wubiuefi exe file and iso file are same folder.
I also used --isopath command option, but not loaded.
There is casper/initrd.lz4 in iso file. Not casper/initrd, casper/initrd.lz and casper/initrd.gz. I think this is reazon.
What do I do to use Zorin iso file by wubiuefi? casper/initrd.lz4 is not supported?
Thanks.

**Comment by hakuna-m** [comment]
You are right, currently Wubiuefi contains no desktop environment for **casper/initrd.lz4**.

It is no problem to add a new configuration in [isolist.ini](https://github.com/hakuna-m/wubiuefi/blob/master/data/isolist.ini) for a new desktop environment. But we need your help.

We need changed names of these 5 files:

```
.disk/info
casper/vmlinuz
casper/initrd
casper/filesystem.squashfs
md5sum.txt
```

**casper/initrd** should be **casper/initrd.lz4**. But are there also other changes ?

Additionally, we need the info if the installer is compatible with the one in Ubuntu. You can test that by changing the ISO and vmlinuz/initrd files from a supported one.  

- Download a small supported ISO or use an existing supported ISO
- Download the ISO of your distro 
- Download Wubiuefi

- Run wubi.exe with the supported ISO. When it tells you to reboot, select "Reboot later".
- Replace **C:\ubuntu\install\installation.iso** with the ISO of your distro (renaming to installation.iso)
- Mount the ISO of your distro and copy **initrd** and **vmlinuz** from the **/casper/** directory over the one in **C:\ubuntu\install** (renaming initrd and vmlinuz to the existing file names of the supported ISO)
- Reboot the computer
- Select the name of the supported desktop environment
- Watch install of your ISO
- Reboot, select the name of the supported desktop environment and boot into your new install.

**Comment by hakuna-m** [comment]
> (initrd and vmlinuz files are in C:\ubuntu\install\boot. Not C:\ubuntu\install.)

Thanks, of course, you are right. I changed the description im my previous post. Maybe, other users read the descrption and want to check other unsupported distros.

> In Zorin iso file, changed file name is casper/initrd only. other file names are same.
> I changed iso, vmlinuz and initrd files from supported one to Zorin one. The installation and booting Zorin is successfully.

OK, so I will create a new desktop environment "Wubi lz4" with your information.

**Comment by hakuna-m** [comment]
I created a new release. https://github.com/hakuna-m/wubiuefi/releases/tag/2004r344 

The new release should work without workaround for Zorin 16 with desktop environment "Wubi lz4".

Can you test the new release and report errors if necessary ?  Thanks.

**Comment by shohtanedu** [comment]
Thanks a lot.
I tested new installer with Zorin iso, but installer is not loaded Zorin iso. I also used --isopath command option, but not loaded.
In wubi-20.04-rev344.log file in temp folder, there is this error: Distro: 'NoneType' object has no attribute 'group'.
```
09-03 00:04 DEBUG  Distro:   checking Wubi lz4 ISO c:\tmp\Zorin-OS-16-Core-64-bit-r1.iso
09-03 00:04 DEBUG  WindowsBackend:   extracting .disk\info from c:\tmp\Zorin-OS-16-Core-64-bit-r1.iso
09-03 00:04 DEBUG  Distro:   parsing info from str=Zorin-OS 16 Core 64bit

09-03 00:04 ERROR  Distro: 'NoneType' object has no attribute 'group'
```

**Comment by hakuna-m** [comment]
> `09-03 00:04 DEBUG  Distro:   parsing info from str=Zorin-OS 16 Core 64bit`

Zorin uses not the same .disk\info pattern as Ubuntu. A similar issue was #282 but the Zorin pattern is more different.

Nevertheless, I try to fix it.

**Comment by hakuna-m** [comment]
I updated the new release for the .disk/info issue: https://github.com/hakuna-m/wubiuefi/releases/tag/2004r344

**Comment by shohtanedu** [comment]
Thanks for your update.
I tested new release, the installer loaded Zorin iso file as "wubi lz4".
But new error was occurred after push "install" button.

Here is error window. (Sorry for Non-English window)

![2021-09-03 202353](https://user-images.githubusercontent.com/89796526/131999481-737f1414-e964-4c00-878c-7ef45f12f805.jpg)

Here is log.
```
09-03 20:22 DEBUG  TaskList: New task check_iso
09-03 20:22 DEBUG  TaskList: ### Running check_iso...
09-03 20:22 DEBUG  CommonBackend: Checking C:\tmp\Zorin-OS-16-Core-64-bit-r1.iso
09-03 20:22 DEBUG  Distro:   checking Wubi lz4 ISO C:\tmp\Zorin-OS-16-Core-64-bit-r1.iso
09-03 20:22 INFO   Distro: Found a valid iso for Wubi lz4: C:\tmp\Zorin-OS-16-Core-64-bit-r1.iso
09-03 20:22 DEBUG  CommonBackend: Using distro Wubi lz4  instead of Wubi lz4 amd64
09-03 20:22 ERROR  TaskList: 'NoneType' object has no attribute 'metalink'
Traceback (most recent call last):
  File "\lib\wubi\backends\common\tasklist.py", line 197, in __call__
  File "\lib\wubi\backends\common\backend.py", line 322, in check_iso
AttributeError: 'NoneType' object has no attribute 'metalink'
09-03 20:22 DEBUG  TaskList: # Cancelling tasklist
09-03 20:22 DEBUG  CommonBackend: Trying to use ISO C:\tmp\Zorin-OS-16-Core-64-bit-r1.iso
09-03 20:22 ERROR  root: 'NoneType' object has no attribute 'metalink'
Traceback (most recent call last):
  File "\lib\wubi\application.py", line 58, in run
  File "\lib\wubi\application.py", line 132, in select_task
  File "\lib\wubi\application.py", line 158, in run_installer
  File "\lib\wubi\backends\common\tasklist.py", line 197, in __call__
  File "\lib\wubi\backends\common\backend.py", line 322, in check_iso
AttributeError: 'NoneType' object has no attribute 'metalink'
09-03 20:22 DEBUG  TaskList: New task check_iso
09-03 20:22 DEBUG  CommonBackend: Could not find any ISO or CD, downloading one now
09-03 20:22 ERROR  TaskList: 'NoneType' object has no attribute 'metalink'
Traceback (most recent call last):
  File "\lib\wubi\backends\common\tasklist.py", line 197, in __call__
  File "\lib\wubi\backends\common\backend.py", line 621, in get_iso
  File "\lib\wubi\backends\common\backend.py", line 416, in download_iso
AttributeError: 'NoneType' object has no attribute 'metalink'
09-03 20:22 DEBUG  TaskList: # Cancelling tasklist
09-03 20:22 DEBUG  TaskList: # Finished tasklist
```

**Comment by hakuna-m** [comment]
Ok. new try:  https://github.com/hakuna-m/wubiuefi/releases/tag/2004r344

I set architecture of an unknown distro to architecture of the CPU. So there is always a matching architecture (in your case "amd64" = 64bit) and fallback is not used.

**Comment by shohtanedu** [comment]
I tested new installer. Finally, installation and booting Zorin is successfully!!
You've been very helpful. Thank you for your time.

**Comment by tronglh241** [comment]
> You are right, currently Wubiuefi contains no desktop environment for **casper/initrd.lz4**.
> 
> It is no problem to add a new configuration in [isolist.ini](https://github.com/hakuna-m/wubiuefi/blob/master/data/isolist.ini) for a new desktop environment. But we need your help.
> 
> We need changed names of these 5 files:
> 
> ```
> .disk/info
> casper/vmlinuz
> casper/initrd
> casper/filesystem.squashfs
> md5sum.txt
> ```
> 
> **casper/initrd** should be **casper/initrd.lz4**. But are there also other changes ?
> 
> Additionally, we need the info if the installer is compatible with the one in Ubuntu. You can test that by changing the ISO and vmlinuz/initrd files from a supported one.  
> 
> - Download a small supported ISO or use an existing supported ISO
> - Download the ISO of your distro 
> - Download Wubiuefi
> 
> - Run wubi.exe with the supported ISO. When it tells you to reboot, select "Reboot later".
> - Replace **C:\ubuntu\install\installation.iso** with the ISO of your distro (renaming to installation.iso)
> - Mount the ISO of your distro and copy **initrd** and **vmlinuz** from the **/casper/** directory over the one in **C:\ubuntu\install\boot** (renaming initrd and vmlinuz to the existing file names of the supported ISO)
> - Reboot the computer
> - Select the name of the supported desktop environment
> - Watch install of your ISO
> - Reboot, select the name of the supported desktop environment and boot into your new install.

Hi @hakuna-m, Zorin OS 17 was released and I tried to install it step by step as you said. It booted successfully but it didn't install automatically. Do you have any workarounds for this issue? Thanks in advance.

**Comment by tronglh241** [comment]
Hi @hakuna-m,

I'm attempting to install Zorin OS 17.1. With the switch from `initrd.lz4` to `initrd.zstd` in this version of Zorin OS, Wubi no longer supports installation as it did with Zorin OS 16. I followed the steps you provided, which worked perfectly for the installation process.

However, I encountered an issue with the error message `device name already exists.`. In fact, I used version [22044r346](https://github.com/hakuna-m/wubiuefi/releases/tag/22044r346), which you mentioned should resolve this problem, but it seems to persist.

Is there any chance that Wubi will support Zorin OS 17 in the future? Thank you!

**Comment by giohomer** [comment]
I have the same issue with Zorin Os 17 and so on .
casper/intrid is now casper/intrid.zstd

what we can do to install it with wubi? 

thanks

**Comment by tronglh241** [comment]
> Hi [@hakuna-m](https://github.com/hakuna-m),
> 
> I'm attempting to install Zorin OS 17.1. With the switch from `initrd.lz4` to `initrd.zstd` in this version of Zorin OS, Wubi no longer supports installation as it did with Zorin OS 16. I followed the steps you provided, which worked perfectly for the installation process.
> 
> However, I encountered an issue with the error message `device name already exists.`. In fact, I used version [22044r346](https://github.com/hakuna-m/wubiuefi/releases/tag/22044r346), which you mentioned should resolve this problem, but it seems to persist.
> 
> Is there any chance that Wubi will support Zorin OS 17 in the future? Thank you!

Update: I fixed the issue by modifying `/boot/grub/grub.cfg`, changing `loop0` to `loop1` in the Zorin menu entry, as noted in [[this comment](https://github.com/hakuna-m/wubiuefi/issues/345#issuecomment-1992637565)](https://github.com/hakuna-m/wubiuefi/issues/345#issuecomment-1992637565). While release 22044r346 doesn’t resolve it, manual editing does.

**Comment by tronglh241** [comment]
> I have the same issue with Zorin Os 17 and so on . casper/intrid is now casper/intrid.zstd
> 
> what we can do to install it with wubi?
> 
> thanks

I installed Zorin 17 using the following steps:  

1. Download [wubiuefi 22044r346](https://github.com/hakuna-m/wubiuefi/releases/tag/22044r346).  
2. Download the Zorin 16 and Zorin 17 ISOs.  
3. Place `wubi22044r346.exe`, along with the Zorin 16 and Zorin 17 ISOs, in the same folder.  
4. Run `wubi22044r346.exe`; it will install using the Zorin 16 ISO.  
5. Delete `C:\ubuntu\install\installation.iso`, then copy the Zorin 17 ISO to `C:\ubuntu\install\` and rename it to `installation.iso`.  
6. Open the Zorin 17 ISO and copy `vmlinuz` and `initrd.zstd` from `/casper/` to `C:\ubuntu\install\boot`.  
7. Delete the old `initrd.lz4` and rename `initrd.zstd` to `initrd.lz4`. 
8. Restart your system.
