### ISSUE TITLE
The app doesn't work in any either modes (download .iso or local .iso file)

### ISSUE THREAD

**Issue by hreffero** [hakuna-m/wubiuefi#316]
Hi,

1. If the app tries to download an .iso it links to the old files that not available anymore (as minor distro updates have been released since)

`09-22 13:02 DEBUG  CommonBackend: Could not find any ISO or CD, downloading one now`
`09-22 13:02 DEBUG  TaskList: New task get_metalink`
`09-22 13:02 DEBUG  TaskList: ### Running get_metalink...`
`09-22 13:02 DEBUG  downloader: downloading http://releases.ubuntu.com/22.04/ubuntu-22.04-desktop-amd64.list > C:\ubuntu\install`
`09-22 13:02 ERROR  CommonBackend: Cannot download metalink file http://releases.ubuntu.com/22.04/ubuntu-22.04-desktop-amd64.list err=[Errno 14] HTTP Error 404: Not Found`
`09-22 13:02 DEBUG  downloader: downloading http://cdimage.ubuntu.com/daily-live/pending/jammy-desktop-amd64.list > C:\ubuntu\install`
`09-22 13:02 ERROR  CommonBackend: Cannot download metalink file2 http://cdimage.ubuntu.com/daily-live/pending/jammy-desktop-amd64.list err=[Errno 14] HTTP Error 404: Not Found`
`09-22 13:02 DEBUG  TaskList: ### Finished get_metalink`
`09-22 13:02 ERROR  TaskList: Cannot download the metalink and therefore the ISO`

**ubuntu-22.04-desktop-amd64.list** doesn't exist anymore since 22.04.01 released > https://releases.ubuntu.com/22.04/ubuntu-22.04.1-desktop-amd64.list

2. If I try a local .iso option (say with the original 22.04 .iso) then the app hard crashes

`09-21 19:03 DEBUG  TaskList: ## Running get_iso...`
`09-21 19:03 DEBUG  CommonBackend: Trying to use pre-specified ISO C:\Downloads\ubuntu-mate-22.04-desktop-amd64.iso`
`09-21 19:03 ERROR  TaskList: 'ascii' codec can't decode byte 0xda in position 24: ordinal not in range(128)`
`Traceback (most recent call last):`
  `File "\lib\wubi\backends\common\tasklist.py", line 197, in __call__`
  `File "\lib\wubi\backends\common\backend.py", line 618, in get_iso`
  `File "\lib\wubi\backends\common\backend.py", line 510, in get_prespecified_iso`
`UnicodeDecodeError: 'ascii' codec can't decode byte 0xda in position 24: ordinal not in range(128)`
`09-21 19:03 DEBUG  TaskList: # Cancelling tasklist`
`09-21 19:03 DEBUG  TaskList: # Finished tasklist`
`09-21 19:03 ERROR  root: 'ascii' codec can't decode byte 0xda in position 24: ordinal not in range(128)`
`Traceback (most recent call last):`
  `File "\lib\wubi\application.py", line 58, in run`
  `File "\lib\wubi\application.py", line 132, in select_task`
  `File "\lib\wubi\application.py", line 158, in run_installer`
  `File "\lib\wubi\backends\common\tasklist.py", line 197, in __call__`
  `File "\lib\wubi\backends\common\backend.py", line 618, in get_iso`
  `File "\lib\wubi\backends\common\backend.py", line 510, in get_prespecified_iso`
`UnicodeDecodeError: 'ascii' codec can't decode byte 0xda in position 24: ordinal not in range(128)`

**Comment by hakuna-m** [comment]
There are two different issues:

> ```
> 09-21 19:03 ERROR TaskList: 'ascii' codec can't decode byte 0xda in position 24: ordinal not in range(128)
> Traceback (most recent call last):
> ```

i.e, position 24 of the file name contains an [Ú (u-acute)](https://en.wikipedia.org/wiki/%C3%9A)

File name "C:\Downloads\ubuntu-mate-22.04-desktop-amd64.iso" does not contain that letter but probably original file name does contain it. Windows path name for downloads often contains a prefix like "C:\Users\Windowsuser\Downloads".

The second issue occurs if there are new releases **and** the old release has been removed. 

> `09-22 13:02 ERROR CommonBackend: Cannot download metalink file http://releases.ubuntu.com/22.04/ubuntu-22.04-desktop-amd64.list err=[Errno 14] HTTP Error 404: Not Found

But no problem, I will edit the file [isolist.ini](https://github.com/hakuna-m/wubiuefi/blob/master/data/isolist.ini) to replace old links with the working new ones.

**Comment by ttibau** [comment]
@hakuna-m  have you updated the links in isolist.ini?  Because I'm still receiving the 404 error message. 

Thanks a lot for the support

**Comment by hakuna-m** [comment]
> have you updated the links in isolist.ini?

I updated it last weekend but i pushed it to repository just few minutes ago: [22041r345](https://github.com/hakuna-m/wubiuefi/releases/tag/22041r345)
